### ISSUE TITLE
[Design] 리뷰, 정보 더 보기 UI 구현(~3/23)

### ISSUE THREAD

**Issue by 0Hooni** [Honzapda/Honzapda_iOS#15]
## 📝 작업 내용
<img width="152" alt="스크린샷 2024-03-19 오후 2 01 46" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/b6c9c8ea-eb9a-47b5-9cc6-821c71fdffae">
<img width="148" alt="스크린샷 2024-03-19 오후 2 02 00" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/a4974783-283a-4bad-beeb-689eee4a9c48">

- MVVM 패턴 적용
- 리뷰 더보기 화면 구현
- 정보 더보기 화면 구현
- `design/#15-more-info-ui`에서 작업합니다

## ✔️ To-Do
- [ ] MVVM 패턴 적용
- [ ] 상세 페이지 메인 → 리뷰 더 보기, 정보 더보기 버튼과 View 연결
- [ ] 리뷰 더보기 View 구현
    - [ ] 기존 View 재사용하기
- [ ] 정보 더보기 View 구현
    - [ ] 기존 View 재사용하기

## 👀 ETC (추후 개발해야 할 것, 참고자료 등)
- 리뷰 더보기 
    - 플로우 구현
    - 버튼 액션 구현
    - API 연결
- 정보 더보기 플로우 구현
    - 플로우 구현
    - 버튼 액션 구현
    - API 연결
