### ISSUE TITLE
[Design] 스플래시 및 온보딩 UI 구현

### ISSUE THREAD

**Issue by youz2me** [Honzapda/Honzapda_iOS#2]
## 📝 작업 내용
<div align="center">
<img width="400" alt="스크린샷 2024-02-28 오후 6 02 43" src="https://github.com/Honzapda/Honzapda_iOS/assets/80394340/97712951-847d-43f7-a770-dd1fbdac6ac2">
</div>

- 스플래시 및 온보딩 UI를 구현합니다.

## ✔️ To-Do
- [ ] 스플래시 화면 UI 구현
- [ ] 온보딩 화면 UI 구현
- [ ] 온보딩 캐러셀 전환 구현
