### ISSUE TITLE
[Design] 리뷰 작성 플로우 UI 구현

### ISSUE THREAD

**Issue by 0Hooni** [Honzapda/Honzapda_iOS#23]
## 📝 작업 내용
<img width="335" alt="1" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/82f47872-64e1-4375-85cf-71c6331c3648"> 
<img width="334" alt="2" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/ea9c597f-6a5c-4daf-93f3-ca1b3fee5cc9">
<img width="330" alt="3" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/df29e297-99c1-402f-8049-81623233e9e2">
<img width="501" alt="4" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/2ee3d430-5231-43c8-8dc9-a41060f24411">

- `design/#23-write-review-flow-ui` 브랜치에서 작업

## ✔️ To-Do
- [x] 리뷰 작성 페이지 구현
    - [x] 사진 추가하기 터치 시 선택창 팝업
    - [x] 방문 날짜 등록 시 팝업
    - [x] 별점 선택 시 개수 하이라이팅
    - [x] 리뷰 내용 작성 TextField
    - [x] 조건에 따른 리뷰 게시 하이라이팅
- [ ] 카메라 촬영 및 등록 구현
    - [ ] 카메라 접근 권한 요구
- [ ] 앨범 사진 선택 및 등록 구현 
    - [ ] 앨범 접근 권한 요구
- [x] 날짜 등록 팝업 뷰 구현

**Comment by 0Hooni** [comment]
참고 1 : 텍스트에디터 배경 색 조정
https://www.linkedin.com/pulse/set-texteditor-background-swiftui-ios-14-s-m-abu-taher

**Comment by 0Hooni** [comment]
팝업, 토스트 메시지 구현을 위한 패키지 추가
https://github.com/exyte/PopupView
