### ISSUE TITLE
[Desgin] 검색 탭 UI 구현

### ISSUE THREAD

**Issue by AIsiteru98** [Honzapda/Honzapda_iOS#24]
## 📝 작업 내용
<img width="108" alt="image" src="https://github.com/Honzapda/Honzapda_iOS/assets/132365672/b8c4ea34-02b2-4107-9d7f-72b8ec8ecd81">
- SearchMainView.swift
<img width="108" alt="image" src="https://github.com/Honzapda/Honzapda_iOS/assets/132365672/f4024904-4d7f-4962-b0ae-8f67a683b8cb">
- SearchView.swift
<img width="108" alt="image" src="https://github.com/Honzapda/Honzapda_iOS/assets/132365672/b303fbfa-71a3-44a9-a436-a2e508e9135e">
- SearchResultView.swift

## ✔️ To-Do
- [x] SearchMainView 완료
    - [x] 로고, 타이틀, 검색창, 최근 검색어 ui 구현
    - [x] 검색창 선택시 SearchView로 전환하도록 함
    - [x] SearchView에서 검색할 때마다 이를 searchViewModel의 recentSearched 배열에 기록 후 이를 받아온다 (pulbished 이용)
- [x] SearchView 완료
    - [x] 크게 상단 검색뷰, 검색뷰 하단, 화면 양측, 탭뷰 윗 부분에 붙어있는 안내 문구(infoView)
- [x] SerachResultView 완료
    - [x] infoView만큼의 크기를 가지도록 설정
    - [x] curationResultView의 card view를 재활용 하여 이를 스크롤 뷰로 설정,
    - [x] 최상단에는 (검색결과 수) (필터 1) (필터 2) 형식으로 구성됨 
    - [x] 소팅 기능은 추후 해야겠지만 필터에 해당하는 값은 해당 cardview에 포함되어야 함
