### ISSUE TITLE
[Design] 스플래시 및 온보딩 UI 구현 (~3/12)

### ISSUE THREAD

**Issue by youz2me** [Honzapda/Honzapda_iOS#3]
## 📝 작업 내용
<div align="center">
<img width="400" alt="스크린샷 2024-02-28 오후 6 02 43" src="https://github.com/Honzapda/Honzapda_iOS/assets/80394340/97712951-847d-43f7-a770-dd1fbdac6ac2">
</div>

- 스플래시 및 온보딩 UI를 구현합니다.
- `design/#3-onboarding-ui` 브랜치에서 작업합니다.
- 3월 12일까지 작업합니다.

## ✔️ To-Do
- [x] 스플래시 화면 UI 구현
- [x] 온보딩 화면 UI 구현
- [x] 온보딩 캐러셀 전환 구현

## 👀 참고자료
https://zeddios.tistory.com/955
https://velog.io/@yimkeul/SwiftUI-Text-내부-특정-글자만-색상-적용
https://odinios.tistory.com/4
https://lafortune.tistory.com/15
