### ISSUE TITLE
[Design] 정보 제공 플로우 구현

### ISSUE THREAD

**Issue by 0Hooni** [Honzapda/Honzapda_iOS#37]
## 📝 작업 내용

<img width="426" alt="스크린샷 2024-05-12 오후 8 50 47" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/03bffb5d-6fab-4f60-9a3d-b7a6525ef315">
<img width="832" alt="스크린샷 2024-05-12 오후 8 51 42" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/a7d54776-0e1f-4328-9f60-a9fefd6aeab9">
<img width="686" alt="스크린샷 2024-05-12 오후 8 52 36" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/88417d23-9529-49c0-910c-3672a57e8efd">
<img width="451" alt="스크린샷 2024-05-12 오후 8 53 42" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/a3dd1bca-149c-4892-b7c2-a0306a22c2e3">

- 전반적인 UI 구현
- 중앙 PlaceHolder를 제공하는 TextField 구현
- 3-Button이 하나만 선택될 수 있게 구현
- 기억나지 않아요 체크 기능 구현(텍스트 입력 차단)
- 기존 CustomDatePicker에 시간 선택 추가
- `design/#37-info-provide-flow-ui` 브랜치에서 작업

## ✔️ To-Do
- [ ] 전반적인 UI 구현
    - [ ] 방문 날짜와 시간 등록
        - [ ] 시간 데이터를 포함하는 DatePicker with half modal 구현
    - [ ] 정보 등록하기
        - [ ] 혼잡도 섹션 구현
        - [ ] 3 버튼 with 기억나지 않아요 체크 버튼
        - [ ] Custom TextField with 기억나지 않아요 체크 버튼

## 👀 ETC (추후 개발해야 할 것, 참고자료 등)
- API 연동을 통한 실제 데이터 CRUD

## 🔥 Issue 속 자신의 Inner Engage
- `커스텀 View`, `Modifier`, `@ViewBuilder`에 대한 명확한 이해 가져가기
- `@State`, `@Binding`, `@ObserverObject` 등 상태 동기화 어노테이션에 대한 상황별 명확한 사용법 가져가기
