### ISSUE TITLE
[Design] 마이페이지 UI 구현

### ISSUE THREAD

**Issue by sedah2102** [Honzapda/Honzapda_iOS#38]
## 📝 작업 내용
<img width="270" alt="스크린샷 2024-05-12 오후 9 19 48" src="https://github.com/Honzapda/Honzapda_iOS/assets/108461678/8051bc2c-785d-421c-8453-835bf2615112"> 
<img width="288" alt="스크린샷 2024-05-12 오후 9 26 36" src="https://github.com/Honzapda/Honzapda_iOS/assets/108461678/5d33a356-817e-4d4d-aa6b-90d988429ff2">

- 마이(user)의 내가 찜한 카페, 도움말, 로그아웃 UI 구현합니다.
- ``에서 작업합니다.
- project파일 오류로 다시 올립니다.

## ✔️ To-Do
- [ ] 내가 찜한 카페 UI 구현
- [ ] 로그아웃 UI 구현
- [ ] 도움말 UI 구현

## 👀 ETC (추후 개발해야 할 것, 참고자료 등)
- API 연결
