### ISSUE TITLE
[Design] 온보딩 UI 구현

### ISSUE THREAD

**Issue by 0Hooni** [Honzapda/Honzapda_iOS#47]
## 📝 작업 내용
- `design/#47-onboarding-ui` 브랜치에서 작업

|    작업 내용    |   UI   |
| :-------------: | :----------: |
| 스플래시 및 로그인 | <img width="293" alt="스크린샷 2024-05-28 오후 1 51 11" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/5b310343-591d-4d17-8de4-d229b2baba06"> |
| 로그인 및 회원가입 약관 | <img width="292" alt="스크린샷 2024-05-28 오후 1 51 24" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/b382be49-c8e6-43f0-a973-039f987ca581"> |
| 로그인 활성화 | <img width="172" alt="스크린샷 2024-05-28 오후 1 52 29" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/57f46e6c-301b-4cc6-8f9f-1e2358315666"> |
| 약관 정보 및 동의 | <img width="350" alt="스크린샷 2024-05-28 오후 1 52 40" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/214c8451-3c1a-473d-9629-b163e36b6aaa"> |
| 회원가입 정보 입력 | <img width="523" alt="스크린샷 2024-05-28 오후 1 52 55" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/1ee756b4-a171-49d6-abf5-89f901fc4a68"> |
| 가입완료 및 취향 생성 | <img width="345" alt="스크린샷 2024-05-28 오후 1 53 05" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/1617f9cf-50c2-413b-963b-e06413e68da0"> |

## ✔️ To-Do
- [x] 스플래시 화면 구현
- [x] 온보딩 화면 구현
    - [x] 캐러셀 사용
- [x] 로그인 화면 구현
    - [ ] TextField 조건 만족 시 버튼 활성화 UI
- [x] 약관 동의 화면 구현
    - [x] 각 항목 터치시 약관 내용이 보이는 하프 모달 구현
    - [x] 하프 모달에서 동의했을 경우 약관 버튼 체크 UI로 변경
- [x] 회원가입 UI 구현
    - [ ] 조건 미달 시 미달된 내용 하단에 표시
    - [x] 조건 달성 시 다음 버튼 활성화
- [ ] 회원가입 완료 화면 구현
- [x] 유저 취향 생성 UI 구현
