### ISSUE TITLE
[Feat] 로그인, 회원가입 기능 구현

### ISSUE THREAD

**Issue by 0Hooni** [Honzapda/Honzapda_iOS#49]
## 📝 작업 내용
- `feat/#49-signup-login-feat` 브랜치에서 작업
- 회원가입 기능 구현
- 로그인 기능 구현
- 일부 구현이 덜 된 디자인 부분 추가

## ✔️ To-Do
- [ ] 일반 유저 회원 가입 기능 구현
    - [ ] 일반 유저 회원 가입 API 연결
    - [ ] 회원 가입 - ID중복 확인  API 연결
    - [ ] 비밀번호 확인 기능 구현
- [ ] 일반 로그인 기능 구현
    - [ ] 일반 로그인 API 연결
    - [ ] 자동 로그인 구현
- [ ] 소셜 로그인 기능 구현
    - [ ] 소셜 로그인 API 연결
- [ ] 일부 미구현된 애니메이션 구현

## 👀 ETC (추후 개발해야 할 것, 참고자료 등)
- 회원가입 중 닉네임 작성 파트 디자인 생성완료시 API를 통한 닉네임 검사
- 아이디, 비밀번호 찾기 UI 구현 및 API 연결
