### ISSUE TITLE
[Design] MapKit을 이용해서 HomeView UI구성

### ISSUE THREAD

**Issue by AIsiteru98** [Honzapda/Honzapda_iOS#6]
## 📝 작업 내용

<img width="548" alt="image" src="https://github.com/Honzapda/Honzapda_iOS/assets/132365672/5f5f7831-e327-4779-9578-9aead1dddc3c">

- MapKit을 중심으로 홈화면 지도를 재구성한다. 
- [design/#6-homeview-ui] 브렌치에서 작업

## ✔️ To-Do

# 맵킷에서 해야 할 것

- [x] 홈화면에서 화면 크기로 지도 표출하기
- [ ] 홈 화면의 좌표를 현재 내 위치로 고정하기
- [ ] 홈 화면의 카메라를 현재 내 위치를 중심으로 설정하기
- [ ] 갱신 주기 설정하기 ( ex : 거리가 5미터 이상 변경되면 좌표 이동과 함께 카메라를 갱신해야 하는가? ) 

# 뷰모델과 의존성 설계하기

- [ ] 펴블리셔로  받아야 할 것과 자체 프라이빗 스테이트로 해야 할 것을 판단하기 (해당 부분은 회의에서 추가 논의 후 설계)

# 홈화면 CardView 구성하기 및 고도화

- [ ] 해당 기능은 우선 기존 프로젝트 것을 끌어다 쓴 후 추가 설계 예정 

# 홈화면 버튼 기능 구성
  - [ ] 내 위치 버튼 : 카메라의 위치를  내 위치로 재설정
  - [ ] 저장된 카페 내역 버튼 : 저장 된 카페 바텀시트를 끌어올리도록 설계
  - [ ] POI 선택시 CardView 노출
  
# POI구성
- 아래는 추가적으로 변동성을 가진다 
  - [ ] POI는 내 위치 기준으로 20개를 생성하도록 하며 중복되지 않도록 한다. 
  - [ ] POI는 하나의 구조체로 관리한다.
  - [ ] POI는 longtitude, latitude, storeId, storeIsSaved를 가진다.
