### ISSUE TITLE
[Design] 상세페이지 메인 UI 구현 (~3/16)

### ISSUE THREAD

**Issue by 0Hooni** [Honzapda/Honzapda_iOS#7]
## 📝 작업 내용
<img width="776" alt="스크린샷 2024-03-01 오전 2 22 49" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/7bde0ecc-ea5a-4089-be4d-872574b7f4b0">
<img width="242" alt="스크린샷 2024-03-01 오전 2 24 05" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/6396b8ce-f06e-4688-9aeb-aeb049aa175f">
<img width="245" alt="스크린샷 2024-03-01 오전 2 24 16" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/9a89d6c4-504f-44e4-af43-735c67dc5911">
<img width="244" alt="스크린샷 2024-03-01 오전 2 33 46" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/21dfaf41-7915-451f-aa0d-b7c5b546e866">
<img width="249" alt="스크린샷 2024-03-01 오전 2 33 53" src="https://github.com/Honzapda/Honzapda_iOS/assets/37678646/062f202d-9b84-473d-99f0-a4322f3bc9f2">

- 상세페이지 메인의 전반적인 UI 구현
- ```design/#7-cafe-detail-page-main-ui``` 에서 작업한다

## ✔️ To-Do
- [x] 배너 UI 구현
- [x] 카페 정보 UI 구현
- [x] 혼잡도 UI 구현
- [x] 유저의 도움 정보 UI 구현
- [x] 리뷰 UI 구현

## 👀 ETC (추후 개발해야 할 것, 참고자료 등)
- Store API 연결
- 요일별 혼잡도 도움말 창 생성
- heart 터치 → heart_fill 구현
