### ISSUE TITLE
[Design] 큐레이션 뷰 UI 구현 (~ 3.14)

### ISSUE THREAD

**Issue by AIsiteru98** [Honzapda/Honzapda_iOS#9]
## 📝 작업 내용

<img width="804" alt="image" src="https://github.com/Honzapda/Honzapda_iOS/assets/132365672/d3dcb362-e860-4ca5-8e4b-59a987d341b0">

- 큐레이션 뷰의 ui구현
- design/#9-curationview-ui 에서 작업

## ✔️ To-Do
- [x] 큐레이션 메인 뷰 구현
- [x] 큐레이션 테스트 뷰 구현
- [x] 큐레이션 결과 뷰 구현
